import json
import uuid
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.models.user import User
from app.models.report import Report
from app.models.query import Query
from app.core.exceptions import NotFoundError


REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f8fafc; color: #1e293b; }}
.header {{ background: linear-gradient(135deg, #1e40af, #3b82f6); color: white; padding: 48px 24px; text-align: center; }}
.header h1 {{ font-size: 2rem; margin-bottom: 8px; }}
.header p {{ opacity: 0.9; }}
.content {{ max-width: 1200px; margin: 0 auto; padding: 32px 24px; }}
.section {{ background: white; border-radius: 12px; padding: 24px; margin-bottom: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
.section h2 {{ font-size: 1.25rem; margin-bottom: 16px; color: #1e40af; }}
table {{ width: 100%; border-collapse: collapse; }}
th, td {{ text-align: left; padding: 8px 12px; border-bottom: 1px solid #e2e8f0; }}
th {{ background: #f1f5f9; font-weight: 600; }}
.chart {{ width: 100%; height: 400px; }}
.footer {{ text-align: center; padding: 24px; color: #94a3b8; font-size: 0.875rem; }}
</style>
</head>
<body>
<div class="header"><h1>{title}</h1><p>{description}</p></div>
<div class="content">{sections}</div>
<div class="footer">Generated by DB-GPT on {date}</div>
</body>
</html>"""

SECTION_TEMPLATE = """<div class="section">
<h2>{question}</h2>
{summary}
<div id="chart-{idx}" class="chart"></div>
<script>
var data = {chart_data};
var layout = {layout};
Plotly.newPlot('chart-{idx}', data, layout, {{responsive: true}});
</script>
<table><thead><tr>{headers}</tr></thead><tbody>{rows}</tbody></table>
</div>"""


async def generate_html_report(db: AsyncSession, user: User, title: str, description: str, query_ids: str) -> Report:
    from datetime import datetime
    ids = json.loads(query_ids)
    sections = []

    for idx, qid in enumerate(ids):
        result = await db.execute(select(Query).where(Query.id == qid, Query.user_id == user.id))
        q = result.scalar_one_or_none()
        if not q:
            continue

        data = json.loads(q.result_json) if q.result_json else {"columns": [], "rows": []}
        columns = data.get("columns", [])
        rows = data.get("rows", [])

        try:
            import plotly.express as px
            import pandas as pd
            df = pd.DataFrame(rows, columns=columns)
            if len(columns) >= 2:
                fig = px.bar(df, x=columns[0], y=columns[1], title=q.question)
                chart_json = json.loads(fig.to_json())
                chart_data = chart_json["data"]
                layout = chart_json["layout"]
            else:
                chart_data = [{"type": "table", "header": {"values": columns}, "cells": {"values": list(zip(*rows))}}]
                layout = {}
        except Exception:
            chart_data = [{"type": "table", "header": {"values": columns}, "cells": {"values": list(zip(*rows)) if rows else [[]]}}]
            layout = {}

        summary_html = f"<p>{q.summary}</p>" if q.summary else ""
        headers = "".join(f"<th>{c}</th>" for c in columns)
        row_html = "".join("<tr>" + "".join(f"<td>{v}</td>" for v in row) + "</tr>" for row in rows[:20])

        sections.append(SECTION_TEMPLATE.format(
            question=q.question or "Query Result",
            summary=summary_html,
            idx=idx,
            chart_data=json.dumps(chart_data),
            layout=json.dumps(layout),
            headers=headers,
            rows=row_html,
        ))

    html = REPORT_TEMPLATE.format(
        title=title,
        description=description,
        sections="\n".join(sections),
        date=datetime.now().strftime("%Y-%m-%d %H:%M"),
    )

    report = Report(
        user_id=user.id,
        title=title,
        description=description,
        html_content=html,
        query_ids=query_ids,
        share_token=uuid.uuid4().hex[:16],
    )
    db.add(report)
    await db.commit()
    await db.refresh(report)
    return report
